### ISSUE TITLE
Add new site configuration to VVV

### ISSUE THREAD

**Issue by davetgreen** [mkdo/kapow-setup#7]
At the end of the process we need to add a VVV site configuration to ensure that it can be provisioned, now that VVV has moved away from scanning the `www/` folder.

This just needs appending to `vvv-custom.yml` and should look like this:

```
my-project:
  hosts:
    - my-project.dev
  nginx_upstream: php71
```
NOTE: the `my-project` string needs to be dynamically replaced.
